name: Docker Image Pull Request

on:
  pull_request:
    branches: '*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build without push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: false

# Reference: https://docs.docker.com/ci-cd/github-actions/
