name: Docker Image CI

on:
  push:
    branches: '*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Obtain repository and tag names
        shell: bash
        run: | 
             if [ -z "${{ secrets.DOCKER_HUB_REPO }}" ]; then
                 echo "##[set-output name=repo;]${{ secrets.DOCKER_HUB_USERNAME }}"
             else
                 echo "##[set-output name=repo;]${{ secrets.DOCKER_HUB_REPO }}"
             fi
             echo "##[set-output name=tag;]$(echo ${GITHUB_REF#refs/heads/} | sed 's/^main$/latest/g')"
        id: extract_tag
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.extract_tag.outputs.repo }}/docker-desktop:${{ steps.extract_tag.outputs.tag }}
          cache-from: type=registry,ref=${{ steps.extract_tag.outputs.repo }}/docker-desktop:buildcache
          cache-to: type=registry,ref=${{ steps.extract_tag.outputs.repo }}/docker-desktop:buildcache,mode=max

# Reference: https://docs.docker.com/ci-cd/github-actions/
